export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENT = "SET_INGREDIENT";
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const START_ORDER = 'START_ORDER';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAILED = 'ORDER_FAILED';
export const FETCH_ORDERS_STARTS = 'FETCH_ORDERS_STARTS';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS ';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED ';

export const AUTH_START = 'AUTH_START'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const LOGOUT = 'LOGOUT'



